targets:
  $default:
    sources:
      - "pubspec.yaml"
      - $package$
      - assets/**
      - lib/**
      - swaggers/**
      - swaggers2/**
      - input_folder/**
      - swagger_examples/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/swagger_generated_code/"
          with_base_url: true
          with_converter: true
          use_path_for_request_names: true